routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
*/

Route::get('test', function (Request $request){
	dd(\App\Http\Controllers\CartController::recalCartIfChangeCurrency());

//	$json = file_get_contents('https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5');
	//$obj = json_decode($json);
//    dump(currency());

//	dd($obj);
//	dump(\App\Http\Controllers\CurrencyController::changeCurrency(3220,'uah', 'eur'));
//	dump(\App\Http\Controllers\CurrencyController::getCurrencyIndex());
    //return App::environment();
    //dd(App::getLocale());
//    dd($request);
//    dd(config('app.locale'));
//    dd(App::getLocale());
//    dump(getCurrencyMenu());

});

Route::get('/currency/{currency}', 'CurrencyController@update')->name('currency.change');
//locales
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
// login/register/password reminder
    Route::auth();
//Auth::routes(); - alias
    // redirects

    foreach (config('redirect') as $link => $redirect) {
        // Laravel >5.5
        // Route::redirect(parse_url($link)['path'], $redirect, 301);
        Route::get(parse_url($link)['path'], function () use ($redirect) {
           return redirect($redirect);
        });
    }

// admin login
    Route::get('admincab/login', 'Admin\Auth\LoginController@showLoginForm');
    Route::get('admincab/logout', 'Admin\Auth\LoginController@logout');
// login
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
// account
    Route::group(['prefix' => 'account', 'middleware' => 'auth'], function () {
        Route::get('/', 'AccountController@index')->name('account');
        Route::get('profile', 'AccountController@profile')->name('profile');
        Route::get('wishlist', 'AccountController@wishlist')->name('wishlist');
        Route::get('order/{id}', 'AccountController@order')->name('account.order');
    });
// user
    Route::resource('user', 'UserController');
// payment
    Route::group(['prefix' => 'payment'], function () {
// payment LiqPay
        Route::get('pay/liqpay', 'LiqPayController@index')->name('pay.liqpay');
        Route::get('liqpay/{id}', 'LiqPayController@userResponse')->name('liqpay.user');
        Route::post('liqpay/{id}', 'LiqPayController@serverResponse')->name('liqpay.server');
// payment PayPal
        Route::get('paypal', 'PayPalController@index')->name('pay.paypal');
        Route::get('paypal/{id}', 'PayPalController@userResponse')->name('paypal.user');
        Route::post('paypal/{id}', 'PayPalController@serverResponse')->name('paypal.server');
        Route::get('paypal/cancel/{id}', 'PayPalController@error')->name('paypal.error');
    });
//upload-rom
    Route::get('/upload-form', 'PagesController@uploadForm')->name('upload.form');
//callback
    Route::get('/callback', 'PagesController@callbackForm')->name('callback');
    Route::get('/callback-master-show', 'PagesController@callbackMSForm')->name('callback.ms');
    Route::post('/master-show/store', 'MasterShowController@store')->name('msubs.store');
    Route::get('/certificate-callback/{price_id}', 'PagesController@cetrificate')->name('sertificate.callback');
    Route::post('/certificate-callback/store/{price_id}', 'CertificateController@store')->name('certificate.store');
// home
    Route::get('/', 'PagesController@index')->name('home');
//master show page view
//Route::get('/master-show', 'PagesController@masterShow')->name('master-show');
//flowers-subscription
    Route::get('subscribe', 'PagesController@subsc')->name('flowers-sub');
    Route::post('subscription/store', 'FlowersController@store')->name('subs.store');
    Route::get('subscribe/{slug}', 'Admin\FSubscribersController@subscribePage')->name('flower.subscribe');
// comments
    Route::post('comments/add/{type}/{id}', 'CommentsController@store')->name('comments.store');
// blog
    Route::get('blog', 'PagesController@blog')->name('blog');
    Route::get('category/{id}', 'PagesController@blogcategory')->name('blog.category');
// items
    Route::post('sort', 'ItemsController@sortUpdate')->name('sort');
    Route::get('item/search', 'ItemsController@search')->name('item.search');
    Route::get('sale', 'ItemsController@pageByFilter')->name('sale');
    Route::get('catalog', 'ItemsController@index')->name('catalog');
    Route::get('catalog', 'ItemsController@index')->name('catalog');
    Route::get('catalog/{slug}', 'ItemsController@category')->name('catalog.category');
    Route::get('view/-{id}', 'ItemsController@show')->name('item');
    Route::get('view/{slug}-{id}', 'ItemsController@show')->name('item')->where('slug', '.*');

//photo flowers uploads
    Route::post('upload-photo', 'PhotosController@upload')->name('photo.upload');

    Route::post('buy-one-click', 'BuyController@buyOneClick')->name('buy.one_click');

// invoice
    //Route::get('bank-invoice/{id}', 'CommerceController@invoice')->name('invoice');
// cart
//    Route::get('cart/add/{id}', 'CommerceController@add')->name('cart.add');
//    Route::post('cart/add/{id}', 'CommerceController@add')->name('cart.add.post');
//    Route::get('cart/delete/{key}', 'CommerceController@delete')->name('cart.delete');
//    Route::post('cart', 'CommerceController@update')->name('cart.update');
//    Route::get('cart', 'CommerceController@show')->name('cart');
//    Route::get('checkout', 'CommerceController@checkout')->name('checkout');
//    Route::get('order/{id}', 'CommerceController@orderStatus')->name('order');
//    Route::post('order/complete', 'CommerceController@createOrder')->name('order.complete');
//    Route::get('buy', 'CommerceController@buy')->name('cart.buy');
//Route::post('login', 'Auth\AuthController@login');

	//CART
    Route::get('cart', 'CartController@show')->name('cart');
	Route::get('cart/add/{id}', 'CartController@add')->name('cart.add');
	Route::post('cart/add/{id}', 'CartController@add')->name('cart.add.post');
	Route::post('cart', 'CartController@update')->name('cart.update');
    Route::get('cart/delete/{key}', 'CartController@delete')->name('cart.delete');
    //ORDER
	Route::get('order', 'OrderController@show')->name('order');
	Route::post('order/save', 'OrderController@save')->name('order.save');
	Route::post('order/calendar_save', 'OrderController@calendarSave')->name('order.calendar_save');
	Route::get('order/calendar_save', function(){
		return redirect('/calendar');
	});
	Route::get('bank-invoice/{id}', 'OrderController@invoice')->name('invoice');
	Route::get('order/{id}', 'OrderController@orderStatus')->name('order.view');
    Route::post('order/complete', 'OrderController@complete')->name('order.complete');



    Route::post('send', 'ContactsController@send')->name('send');
    Route::post('send-contact', 'ContactsController@sendContact')->name('contact.send');
    //Route::post('send_shortcode_form', 'ContactsController@send_shortcode_form')->name('send_shortcode_form');
// pages
    Route::get('{slug}', 'PagesController@show')->name('page');
//social autorization
    Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('social-login');
    Route::get('auth/callback/{provider}', 'Auth\LoginController@handleProviderCallback');
});

app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
        'size', 'title', 'created_at', 'img', 'name', 'email', 'phone'
    ];

	public function getImageAttribute()
	{
		if(is_file($this->dir . $this->id . ".jpg")){
			return "/" . $this->dir . $this->id . ".jpg";
		}else{
			return "/img/noimg.png";
		}
	}
}

resources/views/_old_home.blade.php
@extends('layouts.app')
@section('title',  $page->meta_title)
@section('description', $page->meta_description)
@section('content')

    <div id="container">
        <div class="container">
            <div>
                <h1>{{l('home:h1')}}</h1>
            </div>
            <div class="row">
                @foreach($categories as  $n => $category)
                    @if($n == 2)
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 col-xs-offset-1 main_page_item_holder photo_flower_block">
                            <div class="layer-main"></div>
                            <div class="photo_flower_block_inner">
                                <div class="text-center" style="margin-bottom: 15px;">{{l('Завантажте фото сюди')}}</div>
                                <span><i class="fa fa-arrow-circle-down fa-3x download-i" aria-hidden="true"></i></span>
                                <div class="text-center" style="margin-top: 15px;">{{l('І ми зробимо такий букет')}}</div>
                            </div>
                            <div class="h3 col-lg-6">{{l('Букет по фото')}}</div>
                            {{--<img src="{{asset('/img/main-page-photo6.png')}}" alt="" id="main-page-img">--}}
                            {{--<img src="{{asset('/img/main-page-subphoto.png')}}" alt="" id="main-page-img-sub">--}}
                            <img src="/img/main-page-photo6.png" alt="" id="main-page-img">
                            <img src="/img/main-page-subphoto.png" alt="" id="main-page-img-sub">
                        </div>
                    @endif
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 col-xs-offset-1 main_page_item_holder">
                        <a href="{{route('catalog.category',$category->slug)}}">
                            <div class="h3 col-lg-6">{{$category->title}}</div>
                            <img src="{{$category->image(350,350)}}" alt="" id="main-page-img">
                        </a>
                    </div>
                @endforeach
            </div>

            <div class="content page-content">
                {!! $page->content !!}
            </div>

        </div>
    </div>

@endsection
@push('scripts')
<script>
    $(document).on("click", ".download-icon", function () {
        $('.upload-button').click();
        $(this).removeClass('download-icon')
            .addClass('submit-button');
        $('.photo_flower_block').addClass('hover');

        });
        $(document).on("click", ".submit-button", function () {
            $('.input-sumbit').click();
            $(this).removeClass('sumbit-button')
                .addClass('download-button');
            $('.photo_flower_block').removeClass('hover');
        });
</script>
@endpush

resources/views/autogenerate.blade.php
{{l('Замовити :сategory - «:title». Ціна: :price. Цілодобова доставка квітів у Львові')}}
{{l(':сategory - «:title» ❀ Ціна: :price ➜ Доставка квітів та подарунків у Львові 24h/7 ☎ (099) 082 51 52 ❀ Оригінальні букети ❀ Приємні ціни')}}
{{l('Ціна на :title у Львові від :price ☎ (099) 082-51-52 ❀ Доставка весільних букетів ➜ Цілодобово ❀ Консультація флориста ❀ Доступні ціни.')}}
{{l(':title. Замовлення та ціна у м. Львів')}}
{{l('Весільний')}}

resources/views/callback-form.blade.php
<style>
    form div.form-group input {
        border-radius: 0;
    }
    form button[type='submit']{
        border-radius: 0;
    }
</style>

<form action="{{route('send')}}" method="post" class="callback-form" id="mp-callback-form">
    {{csrf_field()}}
    <input type="hidden" name="type" value="CallbackMe">
    <div class="h3 text-center">{{l('Зв’язатись з організатором')}}</div>
    <div class="form-group">
        <input type="text" placeholder="{{l('Ваше ім’я')}}" name="name" class="form-control">
    </div>
    <div class="form-group">
        <input type="text" name="phone" placeholder="{{l('Ваш контактний номер')}}" class="form-control phone-input">
    </div>
    <button type="submit" class="form-control">{{l('Зв’язатись')}}</button>
</form>

resources/views/comments.blade.php
<div id="comments">
    <div class="pane">
        <div class="col-sm-6 col-sm-offset-3">
            <h4>Создать комментарий</h4>

            {!! Form::open(array('route' => ['comments.store','item',$item->id], 'files' => true, 'method' => 'post','class'=>'form-horizontal')) !!}

            <div class="form-group">
                <input name="name" placeholder="Имя" class="form-control" type="text">
            </div>
            <div class="form-group">
                <textarea name="text" cols="30" rows="5" placeholder="Сообщение ..." class="form-control"></textarea>
            </div>
            <button type="submit" class="btn btn-primary btn-flat">Сохранить</button>
            {!! Form::close() !!}
        </div>
    </div>

    <h3>Отзывы о товаре</h3>

    <div class="col-sm-12">

        @foreach(\App\Models\Comment::whereCommentableType('item')->whereCommentableId($item->id)->wherePublic(1)->with('answer')->get() as $comment)
            <div class="commbox">
                <div class="user">
                    <div class="col-sm-3 col-xs-12 lcol">
                        <span class="name">{{$comment->name}}</span>
                    </div>

                    <div class="col-sm-9 col-xs-12 rcol">
                        <div class="combody">
                            {{$comment->text}}
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                @if($comment->answer)
                    <div class="admin">
                        <div class="feedautor col-sm-3"><span class="name">Администратор</span></div>
                        <div class="feedansw col-sm-9">
                            <div class="combody">{{$comment->answer->text}}</div>
                        </div>
                        <i class="fa fa-caret-down"></i>
                    </div>
                @endif
            </div>
        @endforeach
    </div>
</div>

resources/views/footer.blade.php
<div class="container">
    <div id="footer">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" id="social-bar">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pull-left" id="social">
                    @foreach(config('social') as $social => $link)
                        <div class="col-lg-1 col-md-2 col-sm-3 col-xs-6">
                            <a href="{{$link}}" target="_blank" rel="nofollow">
                                <i class="fa fa-{{$social}} fa-2x"></i>
                            </a>
                        </div>
                    @endforeach
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 footer-phone-block pull-right">
                <span class="footer_number">{!! get_config('phone') !!}</span>
            </div>
        </div>


        <div class="col-lg-12 col-md-12 col-sm-12-col-xs-12" id="payment-icons">
          <div class="footer-payment-header">
            <img src="/img/payment-icons/sprite.png" alt="">
            </div>
        </div>
    </div>
</div>

resources/views/master-show.blade.php
@extends('layouts.app')
@section('title',  $page->meta_title)
@section('description', $page->meta_description)
@section('content')

    <div id="subheader">
        <div class="layer"></div>
        <video poster="" id="bgvid" playsinline autoplay muted loop>
            <source src="{{asset('video/' . $video[0])}}" type="video/webm">
            <source src="{{asset('video/'. $video[1])}}" type="video/mp4">
        </video>
        <div class="col-lg-12 subheader-top text-center">
            <a href="/"><img src="{{asset('img/LOGO.png')}}" alt="logo"></a>
            <span>{{l('Запрошує на майстер класи')}}</span>
            <span class="second">{{l('різні тематики')}}</span>
        </div>
        <div class="h1 text-center subheader-middle"><p class="fldata">{{l('Найближчий майстер клас')}} <span>15</span></p><!-- end --></div>
        <div class="h1 text-center subheader-middle second"><p class="fldata">{{l('тема')}} <span>1111a</span></p><!-- end --></div>
        <div class="h4 text-center subheader-bottom fldata">{{l('Львів, вул. Г. УПА, 15')}}</div><!-- end -->
        <a href="{{route('callback.ms')}}" id="callback-btn-master-show"><button type="button" class="btn btn-default">{{l('записатись')}}</button></a>
    </div>

    <div id="container">
        <div class="container master-show">
           <div class="h2 text-center fldata">{{l('Теми найближчих майстер класів')}}</div><!-- end -->
            @foreach($rubric->pages as $num => $page)
                @if ($num % 2 == 0)
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-lg-offset-1 block-odd">
                <div class="col-lg-4" style="text-align: right;">
                    <img src="{{$page->image(250,250)}}" alt="">
                </div>
                <div class="col-lg-8 description" style="padding-top: 0;">
                    <h4>{{$page->title}}</h4>
                    <p style="font-size: 18px;">{{$page->description}}</p>
                    <span class="master_price">{!!$page->content!!}</span>
                    <a href="{{route('callback.ms')}}" class="callback-btn-master-show1"><button type="button" class="btn ms-button">записатись</button></a>
                </div>
            </div>
                @else
                    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-lg-offset-1 block-even">
                        <div class="col-lg-4 pull-right">
                            <img src="{{$page->image(376,250)}}" alt="">
                        </div>
                        <div class="col-lg-8 description" style="padding-top: 0;">
                            <h4>{{$page->title}}</h4>
                            <p style="font-size: 18px;">{{$page->description}}</p>
                            <span class="master_price">{!!$page->content!!}</span>
                            <a href="{{route('callback.ms')}}" class="callback-btn-master-show1"><button type="button" class="btn ms-button">{{l('записатись')}}</button></a>
                        </div>
                    </div>
                @endif
            @endforeach
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-lg-offset-1 no-padding additional-description">
                <p style="font-size: 16px;" class="fldata">{{l('У вартість всіх майстер класів входять усі матеріали, і звичайно ж свої роботи Ви зможете забрати із собою. Невеликі групи, приємна атмосфера. Майстер класи проходять регулярно. Якщо Ви хочете зробити подарунок близькій людині у нас є ПОДАРУНКОВІ СЕТРИФІКАТИ на суму 300, 400, 500 грн або без номіналу')}}.</p><!-- end --></div>
            <div class="row sertificate-block col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="col-lg-3 col-md-3 col-md-offset-1 col-sm-4 col-xs-6 sertificate-block-single">
                    <img src="{{asset('/img/sertificate/300.png')}}" alt="">
                    <p>{{l('Подарунковий сертифікат на суму')}} <span>300 грн.</span></p>
                    <button type="button" id="callback-btn-certificate" data-price="300" class="btn sertificate-btn">{{l('придбати')}}</button>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6 sertificate-block-single">
                    <img src="{{asset('/img/sertificate/400.png')}}" alt="">
                    <p>{{l('Подарунковий сертифікат на суму ')}}<span>400 грн.</span></p>
                    <button type="button" id="callback-btn-certificate2" class="btn sertificate-btn">{{l('придбати')}}</button>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 sertificate-block-single">
                    <img src="{{asset('/img/sertificate/500.png')}}" alt="">
                    <p>{{l('Подарунковий сертифікат на суму ')}}<span>500 грн.</span></p>
                    <button type="button" id="callback-btn-certificate3" class="btn sertificate-btn">{{l('придбати')}}</button>
                </div>
            </div>

            <div class="h3 text-center col-lg-12" style="margin-top: 25px;">{{l('Наші роботи')}}:</div>
            <div class="our-works-photos-holder col-lg-12">
                <div><img src="{{asset('/img/master-show-works/1.png')}}" alt=""></div>
                <div><img src="{{asset('/img/master-show-works/2.png')}}" alt=""></div>
                <div><img src="{{asset('/img/master-show-works/3.png')}}" alt=""></div>
                <div><img src="{{asset('/img/master-show-works/4.png')}}" alt=""></div>
                <div><img src="{{asset('/img/master-show-works/5.png')}}" alt=""></div>
                <div><img src="{{asset('/img/master-show-works/6.png')}}" alt=""></div>
                <div><img src="{{asset('/img/master-show-works/7.png')}}" alt=""></div>
                <div><img src="{{asset('/img/master-show-works/8.png')}}" alt=""></div>
            </div>
        </div>
    </div>

@endsection
@push('scripts')

    {{--<script src="{{asset('/js/jquery.shapeshift.min.js')}}"></script>--}}
<script>
    (function ($) {
        $(document).on('ready', function () {
            // $('.our-works-photos-holder').shapeshift({
            //     // enableDrag:false,
            // });
        });
    })(jQuery);
</script>
@endpush

resources/views/wedding-design-one.blade.php
@extends('layouts.florescence')
@section('title',  $page->meta_title)
@section('description', $page->meta_description)
@section('style')
    <style>
        .wedding_slider {
            position: relative;
            z-index: 99;
        }

        .slick-current {
            width: 300px;
        }

        .slick-current {
            position: relative;
            top: -149px;
            width: 320px !important;
            height: 320px !important;
        }

        .slick-current img {
            width: 100%;
            height: 100%;
            /*position: relative;*/
            /*top: -149px;*/
            /*width: 300px !important;*/
            /*height: 300px !important;*/
            /*left: -65px;*/
        }
    </style>
@endsection
@section('content')

    <div id="container">
        <div class="container">
            <div id="breadcrumb">
                <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
                    <a href="{{route('home')}}" itemprop="url"> <span itemprop="title">{{l('Головна')}}</span> </a> »
                </div>

                @if($rubric)
                    <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
                        <a href="{{route('page',$rubric->slug)}}" itemprop="url">
                            <span itemprop="title">{{$rubric->title}}</span> </a> »
                    </div>
                @endif

                <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
                    <a href="{{route('page',$page->slug)}}" itemprop="url">
                        <span itemprop="title">{{$page->title}}</span> </a>
                </div>

            </div>

            <div class="wedding_item_holder">
                    <div class="description_block row">
                        <img src="{{$page->image}}" alt="" class="wd-bg-img">
                        <div class="outer_block">
                            <div class="col-lg-10 col-lg-offset-1 item_title">
                                <h1>{{$page->title}}</h1>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 item_description">
                                <p>{!! $page->description !!}</p>
                            </div>
                        </div>
                    </div>
                    <div class="wedding_slider">
                        @foreach($page->images as $image)
                            <div style="width: 160px!important;">
                                <a class="wedding_slide" href="{{$image}}">
                                    <img src="{{$page->image(330,330,$image)}}" alt=""> </a>
                            </div>
                        @endforeach
                    </div>
                    <div class="description_short">
                        {!! $page->content !!}
                    </div>
                    <div class="divider"><img src="{{asset('/img/divider.png')}}" alt=""></div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(function () {
            console.log('popupshowed');
            {{--@if(!session('popupshowed'))--}}
            @if(false)
            console.log('popupshowedDo');
            setTimeout(function () {
                $.colorbox({
                    width: 500, height: 400, html: '<div id="form-holder" style="padding:15px;">' +
                    '<h3 style="font-size:18px;">{{l('Вкажіть, будь ласка, дату весілля і наш флорист зв’яжеться з вами найближчим часом')}}</h3>' +
                    '<form action="{{route('send')}}" method="post">' +
                    '{{csrf_field()}}' +
                    '<input type=hidden name=type value=master-show>' +
                    '<label for="name">{{l('Ім’я')}}</label><input style="margin-bottom:15px;" type="text" name=name class="form-control">' +
                    '<label for="phone">{{l('Контактний номер')}}</label><input style="margin-bottom:15px;" type="text" name=phone class="form-control phone-input">' +
                    '<label for="date">{{l('Дата')}}</label><input style="margin-bottom:15px;" type="text" name=date class="form-control date-input">' +
                    '<button type="submit">{{l('Надіслати')}}</button>' +
                    '</form></div>',
                    onComplete: function () {
                        $('#form-holder form').submitter({
                            onError: function (response) {
                                formError($('#form-holder form'), response.responseJSON);
                                $.colorbox.resize();
                            },
                            onSuccess: function (response) {
                                $('#form-holder form').html(response.message);
                                $.colorbox.resize();
                            }
                        });
                    }
                });
            }, 10000);
            @endif
        });
    </script>
@endpush
@php(session(['popupshowed'=>true]))

resources/views/wedding-design.blade.php
@extends('layouts.florescence')
@section('title',  $rubric->meta_title)

@section('description', $rubric->meta_description)
@section('style')
@endsection
@section('content')
    @if(isset($rubric->video_bg) && !empty($rubric->video_bg))
        <div id="video_bg">
            <i id="video_p" class="fas fa-play"></i>
            <i id="video_s" class="fas fa-volume-off"></i>

            {{--<video src="/{{ $rubric->video_bg }}" poster="/img/weddings_bg.png" loop autoplay>--}}
            <video src="/{{ $rubric->video_bg }}" poster="/img/weddings_bg.png" loop muted>
                Sorry, your browser doesn't support embedded videos,
                but don't worry, you can <a href="/{{ $rubric->video_bg }}">download it</a>
                and watch it with your favorite video player!
            </video>
            <a href="#wedding_design"><img id="video_btn" src="/img/wedding_btn.png" alt=""
                                           class="bounce animated infinite"></a>
        </div>
        @section('page_class',  'home wedding_page')
    @else
        @section('page_class',  'wedding_page')
        <div id="wedding_design_line"></div>
    @endif
    <div id="wedding_design">
        <div class="container">
            <div id="breadcrumb">
                <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
                    <a href="{{route('home')}}" itemprop="url"> <span itemprop="title">{{l('Головна')}}</span> </a> »
                </div>

                @if($rubric)
                    <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
                        <a href="{{route('page',$rubric->slug)}}" itemprop="url">
                            <span itemprop="title">{{$rubric->title}}</span> </a>
                    </div>
                @endif

            </div>
            @if (isset($rubric->h1) && !empty($rubric->h1))
                <h1>{{$rubric->h1}}</h1>
            @endif
            <div class="wedding_item_holder">
                @foreach($rubric->pages as $page)
                    <div class="wedding_item">
                        <div class="row no-gutters">

                            @if($loop->iteration % 2)

                                <div class="col-md-6 col-sm-12 item_img">
                                    <a href="{{route('page',$page->slug)}}">
                                        <img class="wedding_item_img" src="{{$page->image}}" alt="{{$page->title}}">
                                    </a>
                                </div>
                                <div class="col-md-6 col-sm-12 ">
                                    <div class="item_text_w">

                                        <h3>{{$page->title}}</h3>
                                        <div class="item_text">
                                            {{getWordsFromText($page->description, 28)}}
                                        </div>

                                        <a class="more_btn vdz_btn"  href="{{route('page',$page->slug)}}">{{l('Детальніше')}}</a>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            @else

                                <div class="col-md-6 col-sm-12 ">
                                    <div class="item_text_w">

                                        <h3>{{$page->title}}</h3>
                                        <div class="item_text">
                                            {{getWordsFromText($page->description, 28)}}
                                        </div>
                                        <a class="more_btn vdz_btn" href="{{route('page',$page->slug)}}">{{l('Детальніше')}}</a>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-12 item_img">
                                    <a href="{{route('page',$page->slug)}}">
                                        <img class="wedding_item_img" src="{{$page->image}}" alt="{{$page->title}}">
                                    </a>
                                </div>
                                <div class="clearfix"></div>
                            @endif
                        </div>
                    </div>

                @endforeach
            </div>
        </div>

        <div id="projects_block">
            <div class="container">
                <div class="header">{!! trans('new_app.Кожне весілля - окрема історія.') !!}</div>
                <div class="header">{!! trans('new_app.Ти маєш це побачити на власні очі!') !!}</div>
                <a href="{!! url('/projects') !!}" class="vdz_btn">{!! trans('new_app.Наші проекти') !!}</a>
            </div>
        </div>

        <div class="container">
            <div class="content">
                {!! $rubric->content !!}
            </div>
        </div>
    </div>

    @include('parts.contacts_block')

@endsection