routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
*/

Route::get('test', function (Request $request){
	dd(\App\Http\Controllers\CartController::recalCartIfChangeCurrency());

//	$json = file_get_contents('https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5');
	//$obj = json_decode($json);
//    dump(currency());

//	dd($obj);
//	dump(\App\Http\Controllers\CurrencyController::changeCurrency(3220,'uah', 'eur'));
//	dump(\App\Http\Controllers\CurrencyController::getCurrencyIndex());
    //return App::environment();
    //dd(App::getLocale());
//    dd($request);
//    dd(config('app.locale'));
//    dd(App::getLocale());
//    dump(getCurrencyMenu());

});

Route::get('/currency/{currency}', 'CurrencyController@update')->name('currency.change');
//locales
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
// login/register/password reminder
    Route::auth();
//Auth::routes(); - alias
    // redirects

    foreach (config('redirect') as $link => $redirect) {
        // Laravel >5.5
        // Route::redirect(parse_url($link)['path'], $redirect, 301);
        Route::get(parse_url($link)['path'], function () use ($redirect) {
           return redirect($redirect);
        });
    }

// admin login
    Route::get('admincab/login', 'Admin\Auth\LoginController@showLoginForm');
    Route::get('admincab/logout', 'Admin\Auth\LoginController@logout');
// login
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
// account
    Route::group(['prefix' => 'account', 'middleware' => 'auth'], function () {
        Route::get('/', 'AccountController@index')->name('account');
        Route::get('profile', 'AccountController@profile')->name('profile');
        Route::get('wishlist', 'AccountController@wishlist')->name('wishlist');
        Route::get('order/{id}', 'AccountController@order')->name('account.order');
    });
// user
    Route::resource('user', 'UserController');
// payment
    Route::group(['prefix' => 'payment'], function () {
// payment LiqPay
        Route::get('pay/liqpay', 'LiqPayController@index')->name('pay.liqpay');
        Route::get('liqpay/{id}', 'LiqPayController@userResponse')->name('liqpay.user');
        Route::post('liqpay/{id}', 'LiqPayController@serverResponse')->name('liqpay.server');
// payment PayPal
        Route::get('paypal', 'PayPalController@index')->name('pay.paypal');
        Route::get('paypal/{id}', 'PayPalController@userResponse')->name('paypal.user');
        Route::post('paypal/{id}', 'PayPalController@serverResponse')->name('paypal.server');
        Route::get('paypal/cancel/{id}', 'PayPalController@error')->name('paypal.error');
    });
//upload-rom
    Route::get('/upload-form', 'PagesController@uploadForm')->name('upload.form');
//callback
    Route::get('/callback', 'PagesController@callbackForm')->name('callback');
    Route::get('/callback-master-show', 'PagesController@callbackMSForm')->name('callback.ms');
    Route::post('/master-show/store', 'MasterShowController@store')->name('msubs.store');
    Route::get('/certificate-callback/{price_id}', 'PagesController@cetrificate')->name('sertificate.callback');
    Route::post('/certificate-callback/store/{price_id}', 'CertificateController@store')->name('certificate.store');
// home
    Route::get('/', 'PagesController@index')->name('home');
//master show page view
//Route::get('/master-show', 'PagesController@masterShow')->name('master-show');
//flowers-subscription
    Route::get('subscribe', 'PagesController@subsc')->name('flowers-sub');
    Route::post('subscription/store', 'FlowersController@store')->name('subs.store');
    Route::get('subscribe/{slug}', 'Admin\FSubscribersController@subscribePage')->name('flower.subscribe');
// comments
    Route::post('comments/add/{type}/{id}', 'CommentsController@store')->name('comments.store');
// blog
    Route::get('blog', 'PagesController@blog')->name('blog');
    Route::get('category/{id}', 'PagesController@blogcategory')->name('blog.category');
// items
    Route::post('sort', 'ItemsController@sortUpdate')->name('sort');
    Route::get('item/search', 'ItemsController@search')->name('item.search');
    Route::get('sale', 'ItemsController@pageByFilter')->name('sale');
    Route::get('catalog', 'ItemsController@index')->name('catalog');
    Route::get('catalog', 'ItemsController@index')->name('catalog');
    Route::get('catalog/{slug}', 'ItemsController@category')->name('catalog.category');
    Route::get('view/-{id}', 'ItemsController@show')->name('item');
    Route::get('view/{slug}-{id}', 'ItemsController@show')->name('item')->where('slug', '.*');

//photo flowers uploads
    Route::post('upload-photo', 'PhotosController@upload')->name('photo.upload');

    Route::post('buy-one-click', 'BuyController@buyOneClick')->name('buy.one_click');

// invoice
    //Route::get('bank-invoice/{id}', 'CommerceController@invoice')->name('invoice');
// cart
//    Route::get('cart/add/{id}', 'CommerceController@add')->name('cart.add');
//    Route::post('cart/add/{id}', 'CommerceController@add')->name('cart.add.post');
//    Route::get('cart/delete/{key}', 'CommerceController@delete')->name('cart.delete');
//    Route::post('cart', 'CommerceController@update')->name('cart.update');
//    Route::get('cart', 'CommerceController@show')->name('cart');
//    Route::get('checkout', 'CommerceController@checkout')->name('checkout');
//    Route::get('order/{id}', 'CommerceController@orderStatus')->name('order');
//    Route::post('order/complete', 'CommerceController@createOrder')->name('order.complete');
//    Route::get('buy', 'CommerceController@buy')->name('cart.buy');
//Route::post('login', 'Auth\AuthController@login');

	//CART
    Route::get('cart', 'CartController@show')->name('cart');
	Route::get('cart/add/{id}', 'CartController@add')->name('cart.add');
	Route::post('cart/add/{id}', 'CartController@add')->name('cart.add.post');
	Route::post('cart', 'CartController@update')->name('cart.update');
    Route::get('cart/delete/{key}', 'CartController@delete')->name('cart.delete');
    //ORDER
	Route::get('order', 'OrderController@show')->name('order');
	Route::post('order/save', 'OrderController@save')->name('order.save');
	Route::post('order/calendar_save', 'OrderController@calendarSave')->name('order.calendar_save');
	Route::get('order/calendar_save', function(){
		return redirect('/calendar');
	});
	Route::get('bank-invoice/{id}', 'OrderController@invoice')->name('invoice');
	Route::get('order/{id}', 'OrderController@orderStatus')->name('order.view');
    Route::post('order/complete', 'OrderController@complete')->name('order.complete');



    Route::post('send', 'ContactsController@send')->name('send');
    Route::post('send-contact', 'ContactsController@sendContact')->name('contact.send');
    //Route::post('send_shortcode_form', 'ContactsController@send_shortcode_form')->name('send_shortcode_form');
// pages
    Route::get('{slug}', 'PagesController@show')->name('page');
//social autorization
    Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('social-login');
    Route::get('auth/callback/{provider}', 'Auth\LoginController@handleProviderCallback');
});

app/Models/Item.php
<?php

namespace App\Models;

use App\Http\Controllers\CurrencyController;
use App\Traits\Image;
use Illuminate\Database\Eloquent\Model;
use Laraplus\Data\Translatable;

class Item extends Model
{

    use Translatable, Image;

    protected $fillable = [
        'title',
        'category_id',
        'date',
        'price',
        'offer',
        'level',
        'slug',
        'img',
        'description',
        'content',
        'filter_id',
        'public',
        'meta_title',
        'meta_description'
    ];

    public $imgDefault = "/img/noimg.jpg";

    public function filter($id)
    {
        if ($filter = $this->filters->where('filter_id', $id)->first()) {
            return $filter;
        }

        return new ItemFilter;
    }

    // $id - filter group

    public function filters($id = false)
    {
        // if its filter group

        if ($id) {
            return $this->filters->load('attr')->mapWithKeys(function ($item) use ($id) {
                if ($item->attr->parent_id == $id and $item->value) {
                    return [$item->id => $item];
                }
                return false;
            });
        }

        // if it all active filters
        return $this->hasMany('App\Models\ItemFilter');
    }

    /*	public function getPriceAttribute($value)
        {
            return number_format($value, 0, '', ' ');
        }*/

    public function getPriceFormattedAttribute()
    {
        return round($this->price / CurrencyController::getCurrency());
    }

    public function category()
    {
        //Для измежания ошибок при создании новых товаров устанавливаем категорию по умолчанию
    	if(empty($this->category_id)){
		    $this->category_id = 1;
	    }
        return $this->belongsTo('App\Models\Category', 'category_id');
    }

    public function getLinkAttribute()
    {
        return route("item", [$this->slug, $this->id]);
    }

//	public function getIsInStockAttribute()
//	{
//		if ($this->stock > 0) return true;
//
//		if ($this->date > date('Y-m-d H:i:s')) return true;
//
//		return false;
//	}

    public function getIsInCartAttribute()
    {
        return collect((new \App\Http\Controllers\CommerceController)->cartitems())->contains('id', $this->id);
    }

    public function getCurrencyAttribute()
    {
        return CurrencyController::getCurrencyIndex();
    }

    public function getDirAttribute()
    {
        return "upload/items/$this->id/";
    }

    public function getImgsAttribute()
    {
        if (!$this->img) {
            return array();
        }
        return array_keys(json_decode($this->img, 1));
    }

    public function getImageAttribute()
    {
        if (empty($this->imgs[0])) {
            return $this->imgDefault;
        }
        return "/" . $this->dir . "big/" . $this->imgs[0];
    }

    public function getThumbAttribute()
    {
        return $this->image(60);
    }

    public function getTitleAttribute($value)
    {
        // if($this->category_id==2 and \Route::getCurrentRoute()->getName()=='item'){
            // return l('Весільний') . ' ' . mb_strtolower($value);
        // }

        return $value;

    }

    public function getMetaTitleAttribute()
    {

        if($this->category_id==2){
            return trans('app.:title. Замовлення та ціна у м. Львів',['title'=>$this->title]);
//            return trans('app.Ціна на :title у Львові від :price ☎ (099) 082-51-52 ❀ Доставка весільних букетів ➜ Цілодобово ❀ Консультація флориста ❀ Доступні ціни',['title'=>$this->title,'price'=>$this->priceFormatted . ' ' . $this->currency]);
        }

        return trans('app.Замовити :сategory - «:title». Ціна: :price. Цілодобова доставка квітів у Львові',['title'=>$this->title,'сategory'=>mb_strtolower($this->category->title),'price'=>$this->priceFormatted . ' ' . $this->currency]);
    }

    public function getMetaDescriptionAttribute()
    {

        if($this->category_id==2){
            return trans('app.Ціна на :title у Львові від :price ☎ (099) 082-51-52 ❀ Доставка весільних букетів ➜ Цілодобово ❀ Консультація флориста ❀ Доступні ціни.',['title'=>mb_strtolower($this->title),'price'=>$this->priceFormatted . ' ' . $this->currency]);
            //return trans('app.Ціна на :title у Львові від :price ☎ (099) 082-51-52 ❀ Доставка весільних букетів ➜ Цілодобово ❀ Консультація флориста ❀ Доступні ціни',['title'=>mb_strtolower($this->category->title),'price'=>$this->priceFormatted . ' ' . $this->currency]);
        }

        return trans('app.:сategory - «:title» ❀ Ціна: :price ➜ Доставка квітів та подарунків у Львові 24h/7 ☎ (099) 082 51 52 ❀ Оригінальні букети ❀ Приємні ціни',['title'=>$this->title,'сategory'=>$this->category->title,'price'=>$this->priceFormatted . ' ' . $this->currency]);
    }

    public static function boot()
    {

        self::created(function ($item) {
        });

        self::saving(function ($item) {
        });

        self::updating(function ($item) {
        });

        self::deleted(function ($item) {
            \File::deleteDirectory($item->dir);
        });

        parent::boot();
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Category;
use App\Models\Item;
use Config;
use Illuminate\Http\Request;
use SimpleImage as Image;
use View;

class CategoriesController extends Controller
{

	public function __construct()
	{

		$this->allitems = Item::select(['id', 'category_id'])->get();
		$this->datacount = $this->allitems->count();

		$data = [
			'document' => [
				'datacount' => $this->datacount
			],
			'categories' => Category::all()->sortBy('title')->load('childrens','parent'),
			'allitems' => $this->allitems
		];

		View::share($data);

	}

	public function index()
	{
		$document = [
			'cats' => Category::whereNULL('parent_id')->with('childrens')->orderBy('level')->get()
		];

		return view('admin.categories.categories', $document);
	}

	public function create()
	{
		return view('admin.categories.create');
	}

	public function store(Request $request)
	{
		$data = array_filter($request->input());
		if (empty($data['slug'])) $data['slug'] = $data['title'];
		$data['slug'] = tolink($data['slug']);
		$category = Category::create($data);

		if ($request->hasFile('img')) {
			$category->img = $this->addImage($request->file('img'), $category);
			$category->save();
		}

		return back()->with('message', 'Категория добавлена');
	}

	public function edit($id)
	{

		$category = Category::find($id);

		foreach (Config::get('app.locales') as $lang => $key) {
			$Categories[$lang] = $category->translate($lang) ? $category->translate($lang) : new Category;
		}

		$document = [
			'title' => 'Редактирование категории',
			'Category' => $category,
			'Categories' => $Categories,
			'route' => ['admin.categories.update', $id],
			'method' => 'put',
		];

		return view('admin.categories.edit', $document);
	}

	public function update(Request $request, $id)
	{
		$data = $request->all();

		$category = Category::find($id);
		$data['parent_id'] = $data['parent_id'] ? $data['parent_id'] : NULL;

		if ($request->hasFile('img')) {
			$data['img'] = $this->addImage($request->file('img'), $category);
		}

		$category->update($data);

        //var_export($data['ua']);
//        var_export($category->getAttributes());
//        exit;
		foreach (Config::get('app.locales') as $lang => $key) {
			if (empty($data[$lang]['slug'])) $data[$lang]['slug'] = $data[$lang]['title'];
			$data[$lang]['slug'] = tolink($data[$lang]['slug']);

			$category->saveTranslation($lang, $data[$lang]);
		}

		return back()->with('message', 'Категория обновлена');
	}

	/**
	 * @param $id
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function destroy($id)
	{
		$category = Category::find($id);

		// items delete with all subcategories
		$ids = array_pluck($this->treeList($category),'id');
		// deleting in foreach to force model ::deleting method
		foreach (Item::whereIn('category_id',$ids)->get() as $item){
			$item->delete();
		}

		$category->delete();
		return back()->with('message', "Категория " . $category->title . " удалена");
	}

	public function sort(Request $request)
	{

		$this->createLevels($request->input('data'));

	}

	private function createLevels($data, $parent_id = false)
	{
		foreach ($data as $level => $it) {
			$item['level'] = $level;

			$item['parent_id'] = $parent_id ? $parent_id : NULL;

			if (!empty($it['children'])) {
				$this->createLevels($it['children'], $it['id']);
			}

			Category::find($it['id'])->update($item);
		}
	}

	public function treeList($category)
	{
		$categories = array();

		if(!$category->childrens->isEmpty()){

			foreach ($category->childrens as $category){
				$categories = array_merge($categories, $this->treeList($category));
			}

		}
		$categories[] = $category;

		return $categories;

	}

	public function addImage($img, $category)
	{

		// getting all of the post data
		$image = array('img' => $img);
		// $f_name = $img->getClientOriginalName();
		// setting up rules
		$rules = array('img' => 'mimes:jpeg,bmp,png,max:' . get_max_file_size()); //mimes:jpeg,bmp,png and for max size max:10000
		// doing the validation, passing post data, rules and the messages
		$validator = \Validator::make($image, $rules);
		if ($validator->fails()) {
			// send back to the page with the input data and errors
			return $validator->errors()->all();
		} else {

			$image = $category->id . ".jpg";

			//clear if there are previous images
			$category->deleteImg($image);

			$img = Image::make($img);
			$img->best_fit(1000, 1600)->save($category->dir . "big/" . $image)->crop(120, 120)->save($category->dir . "small/" . $image);
			return $image;
		}

	}
	
}

resources/views/admin/categories/categories.blade.php
@extends('admin.admin')
@section('sidebar')
    @include('admin.items.sidebar')
@endsection
@section('content')

    @include('admin.categories.create')
    <div class="box box-danger">
        <div class="box-header with-border">
            <h3 class="box-title">Список разделов</h3>
        </div>
        <div class="box-body">
            <div class="dd" id="menu">
                @include('admin.categories.list')
            </div>
        </div>
    </div>
@endsection

@section('javascript')
    <script src="/admin/plugins/nestable/jquery.nestable.js"></script>
    <script>
        $(document).ready(function () {

            var updateOutput = function (e) {
                var list = e.length ? e : $(e.target);

                if (window.JSON) {

                    var data = {
                        '_token' : '{{ csrf_token() }}',
                        'data' : list.nestable('serialize')
                    };

                    $.post('{{route('admin.categories.sort')}}',data);

                } else {
                    alert('JSON browser support required for sorting.')
                }
            };

            $('#menu').nestable({
                group: 1
            }).on('change', updateOutput);


            $('.del').unbind('click').click(function () {
                if (!confirm("При уадалении категории будут удалены все дочерние категории и все товары в этих категориях. Вы уверены?")) {
                    return false;
                }
            })

        });
    </script>
@endsection

resources/views/admin/categories/create.blade.php
<div class="box">
    <div class="box-body">

        {!! Form::open(array('route' => 'admin.categories.store','files' => true, 'method' => 'post')) !!}
        <div class="row">
            <div class="col-xs-5">
                <input class="form-control" placeholder="Новый раздел" name="title" required/>
            </div>
            <div class="col-xs-5">
                {!! Form::select('parent_id', [''=>'Без категории'] + $categories->pluck('title','id')->toArray(),'',array('class'=>'form-control')) !!}
            </div>
            <div class="col-xs-2">
                <input class="btn btn-primary btn-block" type="submit" value="Сохранить">
            </div>
        </div>
        {!! Form::close() !!}
    </div>
    <!-- /.box-body -->
</div>

resources/views/admin/categories/edit.blade.php
@extends('admin.admin')
@section('sidebar')
    @include('admin.items.sidebar')
@endsection
@section('content')

    <!-- Default box -->
    <div class="box">

        <div class="box-body">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs pull-right">
                    @include('admin.lang-pagination')
                    <li class="pull-left header"><i class="fa fa-th"></i> ...</li>
                </ul>
            </div>
            {!! Form::open(array('route' => $route,'files' => true, 'method' => $method)) !!}
            <div class="col-sm-9">
                <div class="tab-content">

                    @foreach ($Categories as $lang => $category)
{{--                        {!! var_dump($category); !!}--}}
                        <div class="tab-pane @if (App::getLocale()==$lang) active @endif" id="tab_{{$lang}}">

                            <div class="form-group">
                                {!! Form::label($lang."[h1]", 'Заголовок h1', array('class' => '')) !!}
                                {!! Form::text($lang."[h1]", $category->h1, array('class'=>'form-control','placeholder'=>'Заголовок h1')) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label($lang."[title]", 'Название категории', array('class' => '')) !!}
                                {!! Form::text($lang."[title]", $category->title, array('class'=>'form-control','placeholder'=>'Название категории')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label($lang."[slug]", 'Ссылка', array('class' => '')) !!}
                                {!! Form::text($lang."[slug]", $category->slug, array('class'=>'form-control','placeholder'=>'Ссылка')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label($lang."[meta_title]", 'Meta title', array('class' => '')) !!}
                                {!! Form::text($lang."[meta_title]", $category->meta_title, array('class'=>'form-control','placeholder'=>'Название позиции')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label($lang."[meta_description]", 'Meta description', array('class' => '')) !!}
                                {!! Form::text($lang."[meta_description]", $category->meta_description, array('class'=>'form-control','placeholder'=>'Название позиции')) !!}
                            </div>

                            <div class="form-group">
                                <div class="form-input-box">
                                    {!! Form::label($lang."[description]", 'Описание', array('class' => '')) !!}
                                    {!! Form::textarea($lang."[description]", $category->description, array('class'=>'form-control')) !!}
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="form-input-box">
                                    {!! Form::label($lang."[content]", 'Контент', array('class' => '')) !!}
                                    {!! Form::textarea($lang."[content]", $category->content, array('class'=>'form-control editor')) !!}
                                </div>
                            </div>

                        </div>
                    @endforeach

                </div>
                <!-- /.tab-content -->
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    {!! Form::label('parent_id', 'Категория', array('class' => '')) !!}
                    {!! Form::select('parent_id', [ null =>'Без категории']+ array_except($categories->pluck('title', 'id')->toArray(),$Category->id),$Category->parent_id,array('class'=>'form-control')) !!}
                </div>

                <img class="thumbnail img-responsive" src="{{$Category->thumb}}?rand={{rand(1,999999)}}">

                <div class="form-group">
                    <div class="form-input-box">
                        {!! Form::label('img', 'Изображение', array('class' => '')) !!}
                        {!! Form::file('img', null, array('class'=>'form-control')) !!}
                    </div>
                </div>

            </div>

            <div class="clearfix"></div>

            <div class="col-sm-12">

                {!! Form::submit('Сохранить', array('class'=>'btn btn-primary')) !!}
            </div>

            {!! Form::close() !!}
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            ...
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
@endsection
@section('javascript')
<script type="text/javascript" src="/admin/plugins/ckeditor/ckeditor.js"></script>
<script src="/admin/plugins/ckeditor/adapters/jquery.js"></script>
<script>
    $('.editor').ckeditor({
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    });
</script>
@endsection

resources/views/admin/categories/list.blade.php
<ol class="dd-list">

    @foreach ($cats->load('childrens')->sortBy('level') as $category)

        <li class="dd-item" data-id="{{$category->id}}">

         <span class="btns pull-right">

				<a data-original-title="Редактировать" data-toggle="tooltip" data-placement="top"
                   href="{{route('admin.categories.edit',['categories'=>$category->id])}}"><i class="fa fa-cog"></i></a>
				{{--<a data-original-title="Видимость" data-toggle="tooltip" data-placement="top"
                   href="/admincab/menu/result.php?command=change_visible&amp;type=1&amp;id=6"><i
                            class="fa fa-check"></i></a>--}}
				<a class="del confirm" data-original-title="Удалить" data-toggle="tooltip" data-placement="top"
                   href="{{route('admin.categories.delete',['categories'=>$category->id])}}"><i
                            class="fa fa fa-times text-danger"></i></a>
			</span>
            <div class="dd-handle">
                <span class="label label-info">{{$category->id}}</span> {{$category->title}}
            </div>
            @if($cats=$category->childrens)
                @include('admin.categories.list')
            @endif
        </li>

    @endforeach

</ol>